const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');
const assetURL = file => `${file}?v=${createHash('sha256').update(fs.readFileSync(path.join(__dirname, '..', file))).digest('hex').slice(0, 12)}`;
const navigation = [
  ['om.html', 'OM OSS'], ['medlemmer.html', 'MEDLEMMER'],
  ['blimedlem.html', 'BLI MEDLEM'], ['heimlaga.html', 'HEIMLAGA'],
  ['utstillinger.html', 'UTSTILLINGER'], ['kontakt.html', 'KONTAKT'],
];
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const facebook = `<a href="https://www.facebook.com/p/Mer%C3%A5ker-kunstforening-100064623312280/" class="nav-link" target="_blank" rel="noopener noreferrer" aria-label="Meråker Kunstforening på Facebook">
  <svg class="w-6 h-6 fill-current" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2C6.477 2 2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.879V14.89h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.989C18.343 21.129 22 16.99 22 12c0-5.523-4.477-10-10-10z"></path></svg>
</a>`;

function layout(file, page, content, assets) {
  const links = navigation.map(([href, label]) => `<a href="${href}" class="nav-link"${href === file ? ' aria-current="page"' : ''}>${label}</a>`).join('\n');
  const logo = assets['images/MeraakerLogoBlack.png'];
  const green = assets['images/MeraakerLogoGreen.png'];
  const structured = { '@context': 'https://schema.org', '@type': 'Organization', name: 'Meråker Kunstforening', url: 'https://merakerkunstforening.no/', logo: 'https://merakerkunstforening.no/images/MeraakerLogoBlack.png', sameAs: ['https://www.facebook.com/Mer%C3%A5ker-kunstforening-100064623312280'] };
  return `<!DOCTYPE html>
<!-- Generated by npm run build. Edit src/pages and src/layout.cjs. -->
<html lang="no">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escape(page.title)}</title>
  <meta name="description" content="${escape(page.description)}">
  <meta name="keywords" content="${escape(page.keywords)}">
  <link rel="canonical" href="${escape(page.url)}">
  <meta name="robots" content="index, follow">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${escape(page.url)}">
  <meta property="og:title" content="${escape(page.socialTitle)}">
  <meta property="og:description" content="${escape(page.description)}">
  <meta property="og:image" content="https://merakerkunstforening.no/images/MeraakerLogoBlack.png">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="${escape(page.url)}">
  <meta name="twitter:title" content="${escape(page.socialTitle)}">
  <meta name="twitter:description" content="${escape(page.description)}">
  <meta name="twitter:image" content="https://merakerkunstforening.no/images/MeraakerLogoBlack.png">
  <script type="application/ld+json">${JSON.stringify(structured)}</script>
  <link href="${assetURL('style.css')}" rel="stylesheet">
  ${content.includes('data-facebook-embed') ? '<link rel="preconnect" href="https://www.facebook.com" crossorigin>' : ''}
  <script src="${assetURL('main.js')}" defer></script>
</head>
<body class="bg-white font-sans antialiased">
  <a href="#main-content" class="skip-link">Hopp til innhold</a>
  <header>
    <nav class="site-nav" aria-label="Hovedmeny">
      <a href="index.html" class="logo-link"${file === 'index.html' ? ' aria-current="page"' : ''}>
        <img id="navLogo" src="${logo.src}" data-default-src="${logo.src}" data-hover-src="${green.src}" alt="Meråker Kunstforening" width="${logo.width}" height="${logo.height}" class="nav-logo" fetchpriority="high">
      </a>
      <hr class="border-t border-brand opacity-30">
      <div class="desktop-menu"><div class="desktop-links">${links}</div>${facebook}</div>
      <hr class="border-t border-brand opacity-30">
      <button type="button" class="mobile-menu-button" hidden aria-label="Åpne meny" aria-expanded="false" aria-controls="mobile-menu">
        <svg class="w-6 h-6" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
      </button>
      <!-- Visible without JavaScript; enhanced into a collapsible menu when ready. -->
      <div id="mobile-menu" class="mobile-menu">${links}${facebook}</div>
    </nav>
  </header>
  ${content}
  <hr class="border-t border-brand-divider max-w-7xl mx-auto opacity-30">
  <footer class="py-4 text-center text-gray-500 font-serif">Meråker kunstforening <span id="currentYear">${new Date().getFullYear()}</span></footer>
  ${file === 'heimlaga.html' ? `<dialog id="gallery-dialog" class="gallery-dialog" aria-labelledby="gallery-caption" aria-describedby="gallery-count">
    <div class="gallery-toolbar"><span id="gallery-count" aria-live="polite"></span><button type="button" class="gallery-close" aria-label="Lukk bildegalleri" autofocus>Lukk</button></div>
    <p class="gallery-status" role="status"></p>
    <figure><img class="gallery-image" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt=""><figcaption id="gallery-caption" class="gallery-caption"></figcaption></figure>
    <div class="gallery-toolbar"><button type="button" class="gallery-prev" aria-label="Forrige bilde">←</button><a class="gallery-original" href="images/Heimlaga_armbaand.jpg" target="_blank" rel="noopener noreferrer">Åpne originalbildet</a><button type="button" class="gallery-next" aria-label="Neste bilde">→</button></div>
  </dialog>` : ''}
</body>
</html>
`.replace(/[ \t]+$/gm, '');
}
module.exports = { layout, navigation };
